### ISSUE TITLE
회원 가입을 진행해 봤는데 오류가 생겼어요

### ISSUE THREAD

**Issue by colleenInKorea** [Hanghae12th-Assemble/Sogonsogon-BE#6]
이유없이 jwtutil을 타는 데, 이게 security 문제 같은데.. 같이 보면 좋을 것 같아요

**Comment by kimregular** [comment]
.antMatchers("/api/**").permitAll() 바꾼 이유가 있을까요? 전부를 열어둬서 로그인에 오류가 있는거 같아요

**Comment by colleenInKorea** [comment]
혹시 security에서 걸려서 토큰이 없다고 뜨는 게 아닐까 싶어서 일단 다 열었었어요 
혹시 다른 방법이 있을 까요?
